name: Prueba de Mantenibilidad - MTTR

on:
  push:
    branches: [ "main", "master" ]

jobs:
  recuperacion:
    runs-on: ubuntu-latest
    steps:
    - name: Descargar el código
      uses: actions/checkout@v4
    
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        
    - name: Instalar pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 12
        
    - name: Instalar dependencias (basado en pnpm-lock.yaml)
      run: pnpm install
      
    - name: Prueba de salud del servidor
      run: node --check server.js